# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-17 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewImages',
            new_name='ViewImage',
        ),
    ]
