# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-17 05:40
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_viewimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewimage',
            name='user',
            field=models.CharField(max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
