# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-17 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_auto_20160817_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
