# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticafication',
            new_name='Notification',
        ),
    ]
